### ISSUE TITLE
Feature Request: Please consider expanding project scope to include decoding

### ISSUE THREAD

**Issue by bidafiwoc** [nayuki/QR-Code-generator#1]
First off, I really like what you've done with your QR-code-generator project.

I came across your work while searching (web + GH + BB) for pure python-based programs to handle QR code decoding / encoding.  Much as you describe in your writeup [1], I found a lot of projects with sub-optimal dev choices---too many external dependencies, insufficient documentation (internal comments and external manuals / examples), incomplete or unfaithful compliance with Denso-Wave and ISO/IEC 18004 standards (models 1&2)---some don't even implement Reed-Solomon.  Anyway, kudos to you for a really clean and concise project:

 * for clearly defined API; 
 * for simultaneous / equal coverage across four in-demand languages;
 * for complete coverage of all 40 versions and 4 EC levels;
 * for avoidance of magic constants;
 * for flexible (MIT) license selection; and
 * for sensible choices about what portions of encoding are included in your library (ie, 3-11 of your "generation procedure" [1]) and what are left up to implementation by library user.

In short, thanks for what you've shared with the O/S community here.

All that being said, I hope to motivate you to please consider expanding your project to include decoding of QR-Codes.  If anything, there's an even more limited ecosystem of open-source QR-code decoders, compared to that of QR-Code encoders.  In the python world, at least, there's pretty much only ZBar (or a multitude of projects which depend upon it); and ZBar's last stable release was in 2009, with no code checkins since 2012 (and it doesn't support modern Python).  Of course, there's also a Python port of ZXing (from native Java), but ZXing is a large (~70k LOC!), all-encompassing framework.  While there are obviously additional decoders in your other target languages (JS, Java, C++), I believe there are similarly fewer choices there, compared to the situation with encoders.

Given what I can sense of your philosophy with this project, I assume you'd consider any type of QR-code image manipulation (necessary for "full-stack" decoding from the analog world) to be well **outside** of scope, and I'm not suggesting otherwise as part of this feature request:  scope would still exclude image capture, deskewing / perspective-correction / contrast-tuning, and (finally) conversion of pixels into a vector QR-code (ie, SVG).  For example, just as you provide the 'to_svg_str()' function in your QRCode class as the final output stage (after which user-code takes over to otherwise manipulate QR codes), perhaps the appropriate scope to accept input for decoding would be a similar 'from_svg_str()' function, or just a logical 2D numeric array (representing input to be decoded).  This would leave all bitmap->vector image manipulation external to your library, and instead in user-supplied code (through custom libraries, PIL/imagemagick, opencv3, etc).

I look forward to your consideration of this feature request, though it significantly expands the scope of your library.  If it's beyond the itch you're proverbially scratching here, I'll continue to enjoy using your library for encoding only.

Thanks, and best wishes for continued success with this (and other) projects!

[1] https://www.nayuki.io/page/qr-code-generator-library

**Comment by nayuki** [comment]
Hello bidafiwoc and thank you for your gracious, well-explained feedback. I appreciate the time you took to include all the important details and make a really polished write-up. =)

Response to miscellaneous topics:

> (web + GH + BB)

De-acronymized as (web + GitHub + Bitbucket). When I was scouting for competitors, I searched Google and [PyPI](https://pypi.python.org/pypi?%3Aaction=search&term=QR+code&submit=search).

> Denso-Wave and ISO/IEC 18004 standards (models 1&2)

I implemented Model 2 and I think everybody else did the same. I have read the Model 1 section described in the ISO specification out of curiosity, but are there any libraries out there that actually implement it?

> some don't even implement Reed-Solomon

I wonder what this means? If a QR code blanks out all the Reed-Solomon ECC codewords, then it won't be decodable by a conventional RS decoder (you'd have to force it to accept the data as-is and ignore all the ECC bytes). Did you mean that they offload the RS encoding to some other library?

>  If it's beyond the itch you're proverbially scratching here, I'll continue to enjoy using your library for encoding only.

Are you building an application that needs to encode and decode QR codes, if I may ask?

**Comment by nayuki** [comment]
Now onto the main question - will I build a QR Code decoder?

Maybe, perhaps. Currently I am missing the understanding of one critical piece of the puzzle, which is Reed-Solomon ECC decoding and the Berlekamp-Massey algorithm. I started reading about this ~5 years ago but haven't gotten anywhere. It would be great if I understood it, because then I can implement the algorithm compactly, handle things like value ranges and overflow correctly, and build strong guarantees about what the algorithm can and can't do.

Your words are quite encouraging! It looks like you've done your research and discovered a noticeable lack of choices in QR Code decoders in terms of languages, code size, etc. If I come to the conclusion that I can make a meaningful and high quality contribution to the set of open-source QR decoders, I would probably do it. I'd even borrow a Berlekamp-Massey algorithm just to make the product work and earmark it for future overhaul once I understand the math behind it.

Rest assured, I would actually take a full-stack approach to QR decoding. Though I wouldn't build the camera app, I would handle all the backend data processing starting from an image raster: recognition of finder patterns, inverse perspective transform, contrast adjustment, pixel snapping, and then all the actual QR decoding procedure with bit scanning and ECC decoding. Although I don't have experience implementing software that covers the first 4 messy analog-ish steps, I think I can implement reasonable heuristics to operate on general (but not pathological) images. Still, the Reed-Solomon Berlekamp-Massey stuff worries me, and I'll have to figure out how to address that problem before I could start working on this project idea.

**Comment by bidafiwoc** [comment]
Hi @nayuki,

Thanks for your inclusive, expeditious reply above.  Sorry for delay in my response now --- busy with work during the week, and needed a bunch of time to aggregate the situation more fully for you (see below) across all four languages of preference.

Responding first to miscellaneous topics:

> I implemented Model 2 and I think everybody else did the same. I have read the Model 1 section described in the ISO specification out of curiosity, but are there any libraries out there that actually implement it?
> 

I'm not sure: I found one codebase (by @metaxm, see below) that claimed it was "Version 1" only, which makes little sense to me if one interprets that strictly according to QR-Code's meaning of "version"; perhaps the developer actually meant "Model 1".  However, all code comments were in Chinese, so I couldn't easily tell.

> > some don't even implement Reed-Solomon
> 
> I wonder what this means? If a QR code blanks out all the Reed-Solomon ECC codewords, then it won't be decodable by a conventional RS decoder (you'd have to force it to accept the data as-is and ignore all the ECC bytes). Did you mean that they offload the RS encoding to some other library?
> 

Your point is completely valid, which is why I was so surprised to find libraries that made the claim as to not implementing RS ECC.  (I'm not referring to those that used external RS libraries, as that's a completely valid engineering decision.)  See packages listed below by @vsergeev and @allenywang (though, please note that I did not explicitly examine the codebase, but just relied upon
developer comments in 'README' files).  Perhaps they are academic coding exercises.

> Are you building an application that needs to encode and decode QR codes, if I may ask?
>

Yes, exactly (smartphone space).  In the absence of QR-Codes, users can just enter information manually in order to exchange info between devices (use-case scenario cannot assume wifi/cell back-haul network connectivity to cloud in order to serve as intermediary).  That's a bit tedious and quite error prone (even for relatively small amounts of information), but always doable if absolutely need-be.

Your existing QR-Code generator definitely gets me (at least) half-way to a real solution!

> Your words are quite encouraging! It looks like you've done your research and discovered a noticeable lack of choices in QR Code decoders in terms of languages, code size, etc.
>

Thank you.  Given that I'm requesting such a significant increase in scope, doing my part in terms of background investigation seems the least of it.  I spent some more time this weekend to provide a much more comprehensive examination of all decoders I could (reasonably) identify online.  I'll follow-up this response with another one that lists all of them, organized somewhat hierarchically, alongside some of my notes on pros/cons for the more important packages.

> Rest assured, I would actually take a full-stack approach to QR decoding. Though I wouldn't build the camera app, I would handle all the backend data processing starting from an image raster: recognition of finder patterns, inverse perspective transform, contrast adjustment, pixel snapping, and then all the actual QR decoding procedure with bit scanning and ECC decoding.
>

That would be wonderful!  Full-stack (especially with few to no external dependencies for image manipulation) is a real boon.

On the topic of analog -> digital pre-decoding conversions, I came across the following academic reference which might be helpful:

  * http://dline.info/fpaper/jdim/v11i3/7.pdf

Also, here's a collection of QR-Codes (with problems in analog domain) to stress-test analog -> digital reliability:

  * http://www.datagenetics.com/blog/november12013/

> Still, the Reed-Solomon Berlekamp-Massey stuff worries me, and I'll have to figure out how to address that problem before I could start working on this project idea.
>

Understood.  If it helps, here are some nice references that I came across:

  * https://en.wikiversity.org/wiki/Reed%E2%80%93Solomon_codes_for_coders
  * See @tomerfiliba's (copiously commented) RS library immediately below
  * https://github.com/qsantos/qrcode/blob/master/DOCUMENTATION
  * https://en.wikipedia.org/wiki/QR_code#Decoding_example

The wikiversity write-up (and tomerfiliba's associated code with comments) seem particularly beneficial for RS decoding.  Further, if it might prove helpful, here are three external RS decoding libraries I identified, while searching for QR code decoders:

  * https://github.com/tomerfiliba/reedsolomon (Pure Python; amazing comments)
  * http://rscode.sourceforge.net/ (C-based)
  * http://sourceforge.jp/projects/reedsolomon (Java-based; comments in Japanese)

Take care,
Bida

(until I post my next reply with full listing of identified packages...)

**Comment by bidafiwoc** [comment]
@nayuki,

I tried to conduct a fairly comprehensive search for all QR decoders in the four languages you currently include in your codebase (Java, C, Javascript, and Python). I even included a few close-source / proprietary packages (of absolutely no interest to me, nor, I would assume, you) that I happened to stumble across. In all, I examined close to 100 packages.

While reasonable people might disagree as to which codebases among these are the most meaningful, I would highlight four:

* [ZXing](https://github.com/zxing/zxing) (native Java)
  + Active development (under Apache v2 license)
  + Many, many wrappers, ports, and forks (counted 50+ [Python + JS + C + Java])
  + Large, complex codebase (~70k LOC) compared to peers
  + Primary unofficial ports (eg, to Python) surprisingly hackish (in self-described terms)

* [ZBar](http://zbar.sourceforge.net/) (native C)
  + Abandoned since 2009 (with LGPL v2.1 license)
  + Numerous wrappers, ports, and forks (counted 18+ [Python + JS + C + Java])
  + Claims to be high-speed (real-time) with small codebase / memory footprint
  + Supports many barcode formats in addition to QR Code

* [Quirc](https://github.com/dlbeer/quirc) (native C)
  + Unclear development future (with BSD license)
  + Some wrappers and ports (counted 3 [Python + JS, & C native])
  + Claims to be high-speed (real-time) with small memory footprint
  + Claims to be robust to imperfect analog QR Code images

* [QrCode](http://qrcode.osdn.jp/) (native Java)
  + Abandoned since 2007 (with GPL v2 license)
  + Some wrappers and ports (counted 6 [Python + JS, & Java native])
  + Japanese code-comments (for vendored Reed-Solomon library)

I choose these primarily as they are the original "upstream" decoders (ie, not ports of or wrappers around other decoding frameworks), and they have some level of acceptance or recognition by the community.  (Should I have relaxed the "upstream" constraint, for example, @LazarSoft's port of ZXing to JavaScript would likely have been added to this list, given how popular it seems [even though it has apparently been abandoned since 2014].  Should I have relaxed the constraint that there be some level of community receptiveness, I might also have included the other QrCode in C, by @qsantos [abandoned as well, back in 2013]).

I find it quite surprising that, among all four (or even six) of these, only one single package (ZXing) is undoubtedly still in active development, while two others are long abandoned (2007 and 2009) and the fourth is in an unclear state of continuation.  Not particularly auspicious for the community of QR decoders...

Now, for your further reference, here's the full list of packages I examined to make the above judgments:


JavaScript Decoders / Scanners:
-------------------------------

* Independent (non-port/-fork/-wrapper) codebases:

  + https://en.osdn.jp/projects/jpqr/
    . Last commit from 2011
    . No documentation
    . All comments in code in Japanese
    . Unclear copyright and licensing
    . Believe it does not handle analog -> QR-Code conversion (only decoding of already extracted QR-Code from image)

  + https://github.com/kaarposoft/qrlogo
    . Last commit from 2011
    . Decoding inspired by Java-based ZXing (per acknowledgements)

  + https://github.com/yanbe/qrcode-as
    . Last commit from 2008
    . Actually written in ActionScript3, and *NOT* Javascript
    . Listed here for completeness (as AS3 and JS are both based on ECMAScript)
    . Same developer as (relatively) influential QrCode library (in Java)

  + http://codecanyon.net/item/qr-code-scanner-and-generator/7646726
    . Closed-source / available for purchase


* Based upon alternative Java- or C-based libraries:

  + https://github.com/LazarSoft/jsqrcode
    . Port of ZXing (large Java-based QR-code framework)
    . Last commit from 2014

  + https://github.com/colkito/qrcode-decoder-js
    . Fork of above LazarSoft (itself, port of Java-based ZXing)
    . Last commit from 2014

  + http://cirocosta.github.io/qcode-decoder/
    . Wrapper around LazarSoft (itself, port of Java-based ZXing)
    . Last commit from 2014

  + https://github.com/asbjornenge/jsqrcode-scanner
    . Wrapper around LazarSoft (itself, port of Java-based ZXing)
    . Last commit from 2013

  + https://github.com/JanUlrich/QR-Decoder
    . Fork of above LazarSoft (itself, port of Java-based ZXing) to FireFox
    . Last commit from 2013

  + https://github.com/SiegfriedEhret/qrfox
    . Wrapper around LazarSoft (itself, port of Java-based ZXing) for FireFox
    . Last commit from 2013

  + https://github.com/coinpunk/qrimagedecoder
    . Wrapper around LazarSoft (itself, port of Java-based ZXing)
    . Last commit from 2014

  + https://github.com/Howitzer/jsqrcode-html5
    . Wrapper around LazarSoft (itself, port of Java-based ZXing)
    . Last commit from 2014

  + https://github.com/alamcordeiro/qrnode
    . Fork of above LazarSoft (itself, port of Java-based ZXing)
    . Appears not to be active development

  + https://github.com/klonikar/qrcodejs
    . Wrapper around LazarSoft (itself, port of Java-based ZXing)
    . Uncertain whether development is active

  + https://github.com/Chalarangelo/qrcodegolf
    . Wrapper around Cirocosta (itself, wrapper around LazarSoft [then ZXing])
    . Designed to add encryption to QR-Codes for passing short messages
    . Active development

  + https://github.com/edi9999/jsqrcode
    . Port of LazarSoft (itself, port of Java-based ZXing)
    . Active development

  + https://github.com/vicapow/jsqrcode
    . Port of LazarSoft (itself, port of Java-based ZXing) to Node.JS
    . Active development

  + https://github.com/dwa012/html5-qrcode
    . Wrapper around LazarSoft (itself, port of Java-based ZXing) for jQuery
    . Active development

  + https://github.com/Kephson/html5qrcodereader
    . Wrapper around LazarSoft (itself, port of Java-based ZXing) for HTML5
    . Active development

  + https://github.com/cozmo/jsQR
    . Port of Java-based ZXing (directly, not through LazarSoft intermediary)
    . Active development

  + https://github.com/zz85/quirc.js
    . Port of Quirc (C-based library, uncertain development continuity)
    . Uncertain whether development is active

  + https://github.com/Karankang007/quirc.js
    . Port of zz85's quirc.js (itself, port of C-based Quirc)
    . Active development

  + https://gist.github.com/kig/0f620414b614afd2e3a5
    . Self-described by developer as "Buggy feature-free"
    . Appears to be "one-off" posted on Gist (not active development)



C or C++ Decoders / Scanners:
-----------------------------

* Independent (non-port/-fork/-wrapper) codebases:

  + http://zbar.sourceforge.net/
    . Canonical, heavily influential C-based library
    . Unofficial ports to Python / Perl / Ruby
    . Claims to be high-speed (real-time) with small codebase / memory footprint
    . Supports many barcode formats in addition to QR Code
    . LGPL v2.1 license
    . Abandoned ~2009 (!!)

  + https://github.com/dlbeer/quirc
    . Promising library, but unknown future
    . Unofficial ports to JS and Python
    . Claims to be high-speed (real-time) with small memory footprint
    . Claims to be robust to imperfect analog QR Code images
    . BSD license (apparently, unusual "0-clause" version)
    . Uncertain development status (two commits since 2013)

  + https://github.com/qsantos/qrcode
    . C-based
    . Last commit from 2013
    . Solid documentation
    . GPL v3 license
    . Believe it does not handle analog -> QR-Code conversion (only decoding of already extracted QR-Code from image)

  + https://github.com/metaxm/QRCode
    . States "QR-Code Version 1 only" (not sure what that means; perhaps QR-Code Model 1 only???)
    . Sparse documentation; only code comments are in Chinese
    . Requires OpenCV external library
    . Active development

  + https://github.com/jemyzhang/M8CameraScaner
    . Last commit 2014 (only two commits since 2009)
    . 100% of comments and documentation are in Chinese


* Based upon alternative C- or Java-based libraries:

  + https://sourceforge.net/projects/qzxing/
    . C++ / Qt port of ZXing (large Java-based QR-code framework) sponsored by Nokia, but since abandoned by Nokia
    . Apparently continued development by community

  + https://github.com/Bomb3rman/QtZXing
    . Fork of abandoned C++ port of ZXing (large Java-based QR-code framework) to support Qt
    . Inspired by QZXing
    . Active development

  + https://github.com/kylemcdonald/ofxZxing
    . Port of ZXing (large Java-based QR-code framework) to C++ openframeworks
    . Last commit in 2013

  + https://github.com/pke/QrCodeScanner
    . Fork of abandoned C++ port of ZXing (large Java-based QR-code framework)
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/chai2010/qrcode
    . Last commit from 2014
    . API & hacking guides are in Japanese
    . Requires OpenCV external library
    . Based upon underlying decoder from NISHI Takao (vendored directly here)
    . All key docs / key code comments from NISHI's source (in original Japanese)

  + https://github.com/josephholsten/libdecodeqr
    . Last commit from 2014 (only two since 2009)
    . C/C++-based
    . LGPL v2.1 license
    . Requires OpenCV external library
    . Based upon underlying decoder from NISHI Takao (vendored directly here)
    . All key docs / key code comments from NISHI's source (in original Japanese)

  + https://github.com/WilliamRen/libdecodeqr
    . Last commit from 2009
    . Based upon underlying decoder from NISHI Takao (vendored directly here)
    . All key docs / key code comments from NISHI's source (in original Japanese)

  + https://github.com/dragen1860/qrdecoder
    . Almost identical to other codebases found on GitHub (without courtesy of reference, acknowledgment, or copyright notices)
    . Likely copy of QZXing
    . Comments are in Chinese
    . Appears to almost be one-off program with just few commits

  + https://github.com/ShongSu/QRCode
    . Almost identical to other codebases found on GitHub (without courtesy of reference, acknowledgment, or copyright notices)
    . Likely copy of QZXing
    . Comments are in Chinese
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/herbyme/zbar
    . Last commit in 2010
    . Fork of ZBar (abandoned C-based library, last updated ~2009)

  + https://github.com/731jerry/LOLQRCode
    . Last commit in 2013
    . Wrapper around ZBar (abandoned C-based library, last updated ~2009)

  + https://github.com/Hiwr/hiwr_code_scanner
    . Wrapper around ZBar (abandoned C-based library, last updated ~2009)

  + https://github.com/r2v/r2v-ios-sample-app
    . Last commit in 2013
    . Wrapper around ZBar (abandoned C-based library, last updated ~2009)

  + https://github.com/rvb91/Ticket-Box
    . Last commit in 2013
    . Wrapper around ZBar (abandoned C-based library, last updated ~2009)



Java Decoders / Scanners:
-------------------------

* Independent (non-port/-fork/-wrapper) codebases:

  + https://github.com/zxing/zxing
    . Canonical, heavily influential Java-based library
    . Official ports to Android
    . Abandoned official ports to C++ / Obj-C / iPhone / ActionScript / JRuby
    . Unofficial ports to Qt / C++ / Ruby / Python / C# / PHP
    . Supports many barcode formats in addition to QR Code
    . Apache v2 license
    . Large code-size for entire framework, compared to peers (~70k LOC)
    . Very active development and commercial backing

  + http://qrcode.osdn.jp/
    . Last commit in 2007
    . GPL v2 license
    . Todo list notes: "Fix bugs in implementation on RS error correction"
    . Identical version imported by developer into GitHub (~2008):
        https://github.com/yanbe/qrcode
    . Identical version listed by same developer at SourceForge JP:
        http://sourceforge.jp/projects/qrcode/
    . Uses vendored Reed-Solomon library via Masayuki Miyazaki
      (http://sourceforge.jp/projects/reedsolomon/); code comments
      in Japanese only

  + http://www.pqscan.com/read-barcode-java/qrcode.html
    . Closed-source / available for purchase

  + http://www.onbarcode.com/
    . Closed-source / available for purchase

  + http://avapose.com/java_barcode_reader/qrcode.shtml
    . Closed-source / available for purchase


* Based upon alternative C- or Java-based libraries:

  + https://github.com/dlazaro66/QRCodeReaderView
    . Fork of ZXing (large Java-based QR-code framework)
    . Focus on Augmented-Reality integration
    . Active development

  + https://github.com/phishman3579/android-quick-response-code
    . Fork of ZXing (large Java-based QR-code framework)
    . Reduces size and scope of original ZXing framework
    . Focus on Android integration
    . Active development

  + https://github.com/martin-kubik/Advanced-QR-Code-reader
    . Wrapper around ZXing (large Java-based QR-code framework)
    . Claims to increase rate of successful detection
    . Uses OpenCV preprocessing
    . Last commit in 2014

  + https://github.com/girishnair12345/GZxing
    . Port of ZXing (large Java-based QR-code framework)
    . Simplifies size and scope of ZXing for convenience
    . Last commit in 2014

  + https://github.com/jeffreyzh/ZXingSimple
    . Port of ZXing (large Java-based QR-code framework)
    . Simplifies size and scope of ZXing for convenience
    . Last commit in 2013

  + https://github.com/lzh9102/qrcode-desktop
    . Wrapper around ZXing (large Java-based QR-code framework)
    . Active development

  + https://github.com/rokuan/qr-decoder
    . Wrapper around ZXing (large Java-based QR-code framework)
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/andraskurucz/QRdecoder
    . Wrapper around ZXing (large Java-based QR-code framework)
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/DarkAvenger36/Classic-QR-Decoder
    . Wrapper around ZXing (large Java-based QR-code framework)
    . Last commit in 2014 (appears to be one-off code dump)

  + https://github.com/Anerle/QRCode
    . Wrapper around QrCode (abandoned Java-based library, last updated ~2007)
    . Wrapper around ZXing (large Java-based QR-code framework)
    . All docs in Chinese
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/eshaaa/QRCODE_DECODER
    . Wrapper around ZXing (large Java-based QR-code framework)
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/regotiss/QR-Reader
    . Wrapper around ZXing (large Java-based QR-code framework)
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/longbiaochen/QRVideo
    . Wrapper around ZXing (large Java-based QR-code framework)
    . Last commit in 2014 (appears to be one-off code dump)

  + https://github.com/nichtemna/QrcodeDecoding
    . Wrapper around ZXing (large Java-based QR-code framework)
    . Last commit in 2013 (appears to be one-off code dump)

  + https://github.com/pollyman/QRCodeTool
    . Wrapper around ZXing (large Java-based QR-code framework)
    . Last commit in 2014 (appears to be one-off code dump)

  + https://github.com/paudroid/QrCodeDecoderFromSdCard
    . Wrapper around ZXing (large Java-based QR-code framework)
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/gil9red/OneShotDecodeQRcode
    . Wrapper around ZXing (large Java-based QR-code framework)
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/xinanadu/ScanQRcode
    . Wrapper around ZXing (large Java-based QR-code framework)
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/carl1990/QRCode-android
    . Wrapper around ZXing (large Java-based QR-code framework)
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/ekowcharles/take_picture
    . Wrapper around ZXing (large Java-based QR-code framework)
    . Last commit in 2013 (appears to be one-off code dump)

  + https://github.com/hieptv1/EDABK1MakeFriendEasily
    . Wrapper around ZXing (large Java-based QR-code framework)
    . Last commit in 2012 (appears to be one-off code dump)

  + https://github.com/haryadi87/Coffeestore
    . Wrapper around ZXing (large Java-based QR-code framework)
    . Last commit in 2013 (appears to be one-off code dump)

  + https://github.com/chetan1011/QRDecoder
    . Wrapper around QrCodeReaderView (itself port of ZXing [large
      Java-based QR-code framework])
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/Kitsopappas/QBIReader
    . Wrapper around ZBar (abandoned C-based library, last updated ~2009)
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/RowlandOti/QRDecoder
    . Wrapper around ZBar (abandoned C-based library, last updated ~2009)
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/akram/qr-decode-akrambenaissi
    . Identical to: http://code.google.com/p/qr-decode-akrambenaissi
    . Wrapper around QrCode (abandoned Java-based library, last updated ~2007)
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/shiffman/QRCode-for-Processing
    . Wrapper around QrCode (abandoned Java-based library, last updated ~2007)
    . Last commit in 2013 (appears to be one-off code dump)

  + https://github.com/fisherTW/qrcode_decoder
    . Wrapper around QrCode (abandoned Java-based library, last updated ~2007)
    . Unclear development status (appears to be one-off code dump)



Python Decoders / Scanners:
---------------------------

* Independent (non-port/-fork/-wrapper) codebases:

  + https://github.com/waidotto/strong-qr-decoder
    . Pure-python decoder (seemingly supporting all 4 levels of error correction)
    . All docs / code-comments in Japanese
    . Single-file, non-object-oriented development
    . MIT license
    . Active development

  + https://github.com/vsergeev/qrd
    . Pure-python decoder
    . Requires PIL external library 
    . Claims to support QR-Codes in versions 1-40
    . States that "BCH and Reed-Solomon error correction not implemented"
    . Single-file, non-object-oriented development
    . Last commit in 2011 (appears to be one-off code dump)

  + https://github.com/allenywang/Python-QR-Decoder
    . Very basic pure-python decoder
    . Lacks all Reed-Solomon decoding
    . Only functions for tiny QR codes (versions < 4)
    . Same developer as RTQR (below), wrapper around ZBar
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/Wysaat/qrcode
    . Claims to provide decoder functionality, but see no such code
    . Last commit in 2013


* Based upon alternative C- or Java-based libraries:

  + https://github.com/svartalf/python-quirc
    . Wrapper around Quirc (C-based library, uncertain development continuity)
    . Uses CTypes interface to Quirc
    . Last commit in 2012

  + https://github.com/oostendo/python-zxing
    . Wrapper around Python port of ZXing (large Java-based QR-code framework)
    . Self-described as "hack subprocess control library ... gives ... reasonable ... interface to ... ZXing command line"
    . Surprised that *primary* unofficial port to ZXing self-describes as "hack"
    . Active development

  + https://github.com/pushkarparanjpe/imagej-qr-decoder
    . Wrapper around Python port of ZXing (large Java-based QR-code framework)
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/Manouchehri/py-zxing-sample
    . Wrapper around Python port of ZXing (large Java-based QR-code framework)
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/Jarrey/python-ipc-zxing
    . Wrapper around Python port of ZXing (large Java-based QR-code framework)
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/holizz/pyxing
    . Wrapper around Python port of ZXing (large Java-based QR-code framework)
    . Last commit in 2009 (appears to be one-off code dump)

  + https://github.com/xamox/python-zxing
    . Fork of Oostendo's python-zxing (itself, wrapper over ZXing [large Java-based QR-code framework])
    . Last commit in 2012 (appears to be one-off code dump)

  + https://pypi.python.org/pypi/zbar
    . Wrapper around ZBar (abandoned C-based library, last updated ~2009)
    . Official port of ZBar library
    . Last commit in 2009

  + https://launchpad.net/qr-tools
    . Wrapper around ZBar (abandoned C-based library, last updated ~2009)
    . Last commit in 2011

  + https://github.com/allenywang/Real-Time-QR-Recognizer-Reader-and-Decoder
    . Wrapper around ZBar (abandoned C-based library, last updated ~2009)
    . Requires OpenCV external library
    . Unclear development status (appears to be one-off code dump)

  + https://github.com/globophobe/qrcodescanner-base
    . Wrapper around ZBar (abandoned C-based library, last updated ~2009)
    . Unclear development status

  + https://github.com/ruscoe/Python-QR-Dump
    . Wrapper around ZBar (abandoned C-based library, last updated ~2009)
    . Requires PIL external library
    . Last commit in 2014 (appears to be one-off code dump)

  + https://github.com/toby20130333/qr-gui
    . Wrapper around ZBar (abandoned C-based library, last updated ~2009)
    . Last commit in 2013

  + https://github.com/krystianpaszek/qrcode_scanner
    . Wrapper around ZBar (abandoned C-based library, last updated ~2009)
    . Requires OpenCV / PIL / numpy / scipy external libraries
    . Last commit in 2014 (appears to be one-off code dump)

  + https://github.com/globophobe/qrcodescanner-base
    . Wrapper around ZBar (abandoned C-based library, last updated ~2009)
    . Requires OpenCV / Pillow / numpy / pygame external libraries
    . Active development

  + https://github.com/HarryCutts/simple-scanner
    . Wrapper around ZBar (abandoned C-based library, last updated ~2009)
    . Requires OpenCV external library
    . Last commit in 2013 (appears to be one-off code dump)

  + http://pyqrcode.sourceforge.net/
    . Wrapper around QrCode (abandoned Java-based library, last updated ~2007)
    . Referenced routinely as working python decoder
    . Last commit in 2013


Please excuse any errors in notes, or oversights in missing (or miscategorized) packages.

**Comment by bidafiwoc** [comment]
@nayuki

After posting the above full list of QR-Code decoders, along with my extracted preference for the four most important packages (only a single one of which is unambiguously still actively developed), I'm surprised to discover that the QR decoding ecosystem is even more sparsely populated with strong, independent code bases, than I had imagined in my first post here (at which point, I had only examined Python code bases).

Anyway, I'll look forward to your consideration of helping to ameliorate this scenario, and wish you the best regardless.

Incidentally, should it be helpful to you, please feel free to repurpose anything I've written in this issue for your own needs --- I hereby release it into public-domain, via [Creative-Commons CC0](https://wiki.creativecommons.org/wiki/Public_domain).

Hope this helps, in some way, and take care,
Bida

**Comment by nayuki** [comment]
Thanks for providing the wonderful information, @bidafiwoc!

I am acknowledging your commentary on version 1 / model 1, encoders without RS ECC, your proposed application for QR Code generation + scanning, DataGenetics' distorted QR codes, links to RS decoding algorithm.

Also I would like to thank you for the time you took to research the currently available QR code decoders and write the lengthy comparison. I like the humor in the "unusual 0-clause BSD license" ;-). It seems there are a lot of abandoned QR code projects out there, and that is sad because it makes it harder to find the worthwhile projects. You are kind for putting the research text in the public domain.

My status update right now is that I did a lot of reading about the RS decoding theory based on at least 5 different tutorials, with all the polynomial and linear algebra goodness. I understand parts of it such as the syndrome calculation and Chien search, but have yet to understand the Berlekamp-Massey algorithm, Forney algorithm, and exactly how to work with the error locator polynomial.

Subsequently, I wrote a private demo program that performs RS encoding (which I already know how to do) and limited RS decoding that can locate and correct a one-symbol error (which is new and experimental, but seems to work properly). It is still a big question at this point whether I can understand the rest of the math to implement a full RS decoder or not. Thanks again for your patience. =)

**Comment by nayuki** [comment]
For the record, I have a preliminary working Reed-Solomon ECC decoder now.

I chose the Peterson-Gorenstein-Zierler algorithm because it is described in the ISO QR Code specification as a decoding example, and because that description plus the [Wikipedia description](https://en.wikipedia.org/wiki/Reed%E2%80%93Solomon_error_correction#Peterson.E2.80.93Gorenstein.E2.80.93Zierler_decoder) was comprehensible enough for me to implement concretely. The algorithm runs in O(k^3) time where k is the number of ECC bytes. This isn't as good as Berlekamp-Massey at O(k^2), but it's a decent start.

It remains to be seen whether I have the time to build out the rest of the logic for scanning QR Codes - such as image detection and segmentation, bit stream parsing, etc.

**Comment by nayuki** [comment]
Published an article now. Math is rigorously justified, and code is reference quality.
https://www.nayuki.io/page/reed-solomon-error-correcting-code-decoder
