### ISSUE TITLE
Javascript qrcodegen module is browser global only

### ISSUE THREAD

**Issue by amvtek** [nayuki/QR-Code-generator#10]
It would be nice to also be able to load this module as
 * commonjs module (usage through webpack & browserify bundlers)
 * AMD module
and also ensure distribution through npm.

This project provide some hints on how to provide "universal module definition"
 * https://github.com/umdjs/umd

To allow usage through commonjs, I just added a line to your code. But it would be better not to have to modify library code.

Bests,
Marc

**Comment by nayuki** [comment]
This JavaScript packaging stuff looks like busywork and long-term churn as fads change. I don't see the return on effort invested to understand the frameworks, nor the justification to write and maintain more lines of code.

**Comment by amvtek** [comment]
I share your perspective on the fad changing problem. However the users of your library may not have a choice, and may discard using your library (which stands out for the clarity of its code) as a result of non compatibility with today leading ecosystems. Additionally by sharing your work on say npm you improve discover ability of your solution. The Python version of your library has a proper setup installer and is distributed through PyPi, this reinsure Python developers that they can commit time integrating it.

If you want I can try tackling packaging your javascript library without changing a line in your qrcodegen.js module.

**Comment by ShahabT** [comment]
+1 to amvtek's point. Opted to https://github.com/soldair/node-qrcode/commits/master exactly because it was very hard to use this lib's typescript version in my react project. if it had been an npm module would go with this liberary.

**Comment by thexeos** [comment]
It is very simple to set up as module for importing. No need to use other, less performant, libraries available on npm.

**Step 1:** Add the following line to the end of the `qrcodegen.ts` file:

    export default qrcodegen

**Step 2:** Use the following line to import `qrcodegen.ts` file anywhere where you need to use this library:

    import qrcodegen from '../your/project/path/to/qrcodegen.ts'

**Done!** You now have access to `qrcodegen.QrCode` in your code.

Likewise, if you are using webpack, you can load the code asynchronously like this:

    const qrcodegen = await import(/* webpackChunkName: "qrcodegen" */ '../your/project/path/to/qrcodegen.ts')

@nayuki, maybe you could add the "`export default qrcodegen`" part in README.md under `/typescript-javascript/`? That could clear up some confusion about namespaces for people that haven't used them in their project before.

**Comment by petrospap** [comment]
Hello, I use your  qrcodegen-v1.7.0-es6.js
Working perfect out of box! Thank you..

but when i try to use it as await import (no matter what i have done) i cant make it work.
what i try to do is 
```
	async buildCodes(p){
	  await import('./qrcodegen.js').then((qrcodegen) => {
		this.qrcodegen = qrcodegen;
		console.dir(this.qrcodegen);
		this.drawCanvas();
		return this.data;
	  });
	}
```

this error i got

```
Object { qrcodegen: {…}, … }
qrcodegen: Object { QrCode: class QrCode, QrSegment: class QrSegment}
QrCode: class QrCode { constructor(version, errorCorrectionLevel, dataCodewords, mask) }​​
QrSegment: class QrSegment { constructor(mode, numChars, bitData) }​​
<prototype>: Object { … }
Symbol(Symbol.toStringTag): "Module"

Uncaught (in promise) TypeError: this.qrcodegen.QrCode is undefined at drawCanvas 
```

in drawCanvas has the line
```qr = this.qrcodegen.QrCode.encodeText(txt, this.qrcodegen.QrCode.Ecc.MEDIUM),```

note this working perfect if i don't use await import and loaded as normal import from.

**Comment by nayuki** [comment]
@petrospap I don't think the problem you're experiencing is related to await import. `QrCode.drawCanvas()` was removed in v1.7.0, in commit [1cc4617d5716](https://github.com/nayuki/QR-Code-generator/commit/1cc4617d57162d99ba27f04d5075ce2ac08562a7). You'll have to copy an implementation from [qrcodegen-output-demo.ts](https://github.com/nayuki/QR-Code-generator/blob/4e41cb2c721a5e06eff75e79fd47a4274f6bb8b0/typescript-javascript/qrcodegen-output-demo.ts#L203-L220) into your own main program.

**Comment by petrospap** [comment]
@nayuki Thank you for your response, the problem is the await import, as if i don't use await everything is working perfect.
seems to me that can't pass out of await **this.qrcodegen**;
probably have to find another way to use await import

**Comment by nayuki** [comment]
Read carefully. At https://github.com/nayuki/QR-Code-generator/releases/tag/v1.7.0 , the source file qrcodegen-v1.7.0-es6.js does not contain `drawCanvas` anywhere.

**Comment by petrospap** [comment]
Yes I know! I take it and i adapted to script.. Anyway I found solution to my problem.
Thanks again for this very helpful script (talking to my self, maybe is time to start TS)
