### ISSUE TITLE
Porting to .NET Core

### ISSUE THREAD

**Issue by jakeoeding** [nayuki/QR-Code-generator#101]
Can we port this project to .NET Core using C#? I am willing to do the work if you are interested in expanding the reach of your library.

**Comment by manuelbl** [comment]
It has already been done: https://github.com/manuelbl/QrCodeGenerator

As @nayuki isn't very familiar with C#, he/she didn't want to include it into this repository. So it's in main repository as well as available through NuGet.

Also see #45

**Comment by jakeoeding** [comment]
Ahh, wonderful! Thanks for pointing me in the right direction. Apologies for not doing enough research before posting.
