### ISSUE TITLE
A change for printQr that makes the qr code acctually scanable

### ISSUE THREAD

**Issue by dhiahassen** [nayuki/QR-Code-generator#103]
It would be nice of you change the character you are using to print the filled squares of the qrCode to "\xB2" that is  ▓ so that it becomes prettier and more scanble with phone camera , because my phone was only able to scan the code after that i made this change : 
`/*---- Utilities ----*/

// Prints the given QrCode object to the console.
static void printQr(const QrCode &qr) {
	int border = 4;
	for (int y = -border; y < qr.getSize() + border; y++) {
		for (int x = -border; x < qr.getSize() + border; x++) {
			std::cout << (qr.getModule(x, y) ? "\xB2\xB2" : "  ");
		}
		std::cout << std::endl;
	}
	std::cout << std::endl;
}`

**Comment by nayuki** [comment]
Non-ASCII characters are vulnerable to the system character encoding settings.
