### ISSUE TITLE
Allow creation of CMYK Color-space BufferedImage and SVG 

### ISSUE THREAD

**Issue by dellgreen** [nayuki/QR-Code-generator#109]
Not all software does a great job of converting RGB to CMYK for high-end printing, would be useful to create images in colorspaces other than RGB. I.e. CMYK, Spot-colour.

Ideally the user would be able to provide the colorspace and colour values required

**Comment by nayuki** [comment]
I'm not aware of Java libraries or application software that handles CMYK as opposed to the ubiquitous RGB. Do you have examples to offer?

**Comment by dellgreen** [comment]
I believe you can use ImageIO and twelveMonkeys with CMYK.

https://stackoverflow.com/questions/46104029/write-image-in-java-with-cmyk-color-space

https://github.com/haraldk/TwelveMonkeys

for my use I planned on using iText/openPDF to create print-quality PDF's

https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/ImgRaw.java#L81

**Comment by nayuki** [comment]
Sorry, I'm going to close this because my intention is to remove the method `QrCode.toImage()` from the library, and instead put it into the demo program (which is non-mandatory).
