### ISSUE TITLE
Generate Qr code for very large txt file

### ISSUE THREAD

**Issue by Tyvain** [nayuki/QR-Code-generator#111]
For artistic purpose, I try to generate a very big qr code (so a very huge image file) base en a large txt file.

When I try to generate for a large txt file I get this error:

Exception in thread "main" io.nayuki.qrcodegen.DataTooLongException: Segment too long
	at io.nayuki.qrcodegen.QrCode.encodeSegments(QrCode.java:161)
	at io.nayuki.qrcodegen.QrCode.encodeSegments(QrCode.java:116)
	at io.nayuki.qrcodegen.QrCode.encodeText(QrCode.java:74)
	at io.nayuki.qrcodegen.QrCodeGeneratorDemo.main(QrCodeGeneratorDemo.java:51)

I use this code:

 ```
public static void main(String[] args) throws IOException {
        String path = "mybigfile.txt";

        try {

            // default StandardCharsets.UTF_8
            String text = Files.readString(Paths.get(path));
            System.out.println(text);
            QrCode.Ecc errCorLvl = QrCode.Ecc.LOW;  // Error correction level

            QrCode qr = QrCode.encodeText(text, errCorLvl);  // Make the QR Code symbol

            BufferedImage img = qr.toImage(10, 4);           // Convert to bitmap image
            File imgFile = new File("mybigfile.txt-QR.png");   // File path for output
            ImageIO.write(img, "png", imgFile);              // Write image to file

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```

**Comment by manuelbl** [comment]
QR codes have limited size. The limit is version 40 corresponding to 177 by 177 black/white dots. Your text is so long it would require an even bigger QR. Thus it's rejected.

**Comment by nayuki** [comment]
Capacity limits: https://en.wikipedia.org/wiki/QR_code#Storage
