### ISSUE TITLE
Any plans to implement C# verison?

### ISSUE THREAD

**Issue by depler** [nayuki/QR-Code-generator#114]
Currently there is no adequate QR encoder for C# - only slow and heavy implementations

**Comment by manuelbl** [comment]
See:

- [Porting to .NET Core](https://github.com/nayuki/QR-Code-generator/issues/101)
- [.NET version of library](https://github.com/nayuki/QR-Code-generator/pull/45)
- [QrCodeGenerator on GitHub](https://github.com/manuelbl/QrCodeGenerator)

**Comment by depler** [comment]
Thanks! This exactly what I looking for, somehow I didn't find it on github
