### ISSUE TITLE
QR-Code in DXF

### ISSUE THREAD

**Issue by froussel** [nayuki/QR-Code-generator#115]
![test QR_pt](https://user-images.githubusercontent.com/2101461/122951588-ad7daf00-d37d-11eb-97e8-fd45690720f3.jpg)
Hello,
I would like to use a CNC machine to engrave qr code with a cylindrical milling cutter 2 sizes.
Would it be possible to have a dxf file of the tool path allowing to obtain a machining image as given in the attached file?
With holes giving circles it also works. It may be easier to modify the part of the program that draws squares and take only the center of the square for the dxf.
Cheers

**Comment by nayuki** [comment]
I am not familiar with the DXF file format. Sorry I can't help you.

**Comment by froussel** [comment]
Sorry
