### ISSUE TITLE
An other shape in svg

### ISSUE THREAD

**Issue by froussel** [nayuki/QR-Code-generator#116]
Hello,

would it be possible to generate svg like
[https://user-images.githubusercontent.com/2508576/68100667-1bcbe000-fec1-11e9-966b-6859f25fb22e.png]
in which the stars are non-secant discs or each square joined from one side to another would form a slightly smaller figure so that the adjacent points of the squares no longer touch each other
Or or have the shape of a toolpath such as
![test QR_pt](https://user-images.githubusercontent.com/2101461/123075448-8922e080-d418-11eb-9ed0-a63838adfb43.jpg)

**Comment by nayuki** [comment]
My repeated answer: https://github.com/nayuki/QR-Code-generator/issues/113

Your related previous issue: https://github.com/nayuki/QR-Code-generator/issues/115
