### ISSUE TITLE
qr code reader suggestion?

### ISSUE THREAD

**Issue by Grabber** [nayuki/QR-Code-generator#121]
@nayuki, thank you so much for sharing this piece of art code. Do you have or recommend any code for the reader?

**Comment by nayuki** [comment]
By searching Google, you can determine that I do not have a QR Code scanner/reader implementation.

I rarely make recommendations in general. Everyone seems to use the [ZXing](https://github.com/zxing/zxing) barcode reader anyway.

Please only use the issues system to point out mistakes in my published code.
