### ISSUE TITLE
Please package for chocolatey

### ISSUE THREAD

**Issue by xeruf** [nayuki/QR-Code-generator#126]
https://chocolatey.org, the package manager for Windows, has not a single QR code generator packaged so far, your chance ;)

**Comment by nayuki** [comment]
Looking at their website, I see full desktop GUI applications being offered. Does Chocolatey host libraries for developers?

**Comment by xeruf** [comment]
That's not really the point, it is to distribute binaries/installers to displace the default chore of installing stuff on Windows.
https://scoop.sh seems more suited for libs.

**Comment by nayuki** [comment]
This project ("QR Code generator") is a library, not a GUI application that a user would be expected to install. I doubt that it belongs on Chocolatey.

**Comment by shellscape** [comment]
@nayuki I think you might have a fundamental misunderstanding of these package managers. Referencing your comments on this issue and the issue/PR about NPM. It's probably best to add a statement to the README that you have no interest in supporting packages for the various managers. And that's totally OK, it's probably just wise to set the expectation for users.

You might also consider staying that package manager support should be handled on forks, where they can be kept up to date with upstream, placing no burden on this repo. 

Either way is probably best, or users will probably continue to be confused and continue opening issues like this.

**Comment by xeruf** [comment]
I actually misread your readme, alright then :)
