### ISSUE TITLE
C# Support (netstandard/Unity)

### ISSUE THREAD

**Issue by Nicolas-Constanty** [nayuki/QR-Code-generator#135]
Hi,
I've ported the Java (fast) version  of your repository into C# (netstandand). I've converted all the files from Java (fast) to C# so I can do a pull request, if you are interested by this version.
I created this port to use it inside my game made with Unity3D, but I took care to only use the standard library so no external libs are required.

Edit: Thanks for your work 👍 !

**Comment by nayuki** [comment]
Thanks to you for the hard work! The leading C# port of this QR library was done by Manuel Bleichenbacher a number of years ago: https://github.com/manuelbl/QrCodeGenerator . I think there is one or two more ports that are less known. Sorry if this means you ended up duplicating the effort.

As I'm not experienced in C#, I don't feel up to the task of maintaining such a port as I make all changes in sync. You should be able to find past instances of this among my GitHub issues and pull requests as other people have tried to propose other language ports.

Cheers!

**Comment by Nicolas-Constanty** [comment]
Hi, nayuki,
I totaly understand, it's already a lot of work to maintain all the supported languages. 
>Sorry if this means you ended up duplicating the effort.

It didn't took me so long to port it, don't feel sorry :).

Thanks you, for providing this code!
