### ISSUE TITLE
I want to use this on my m1 mac, is there a way to use this library with arm based architecture

### ISSUE THREAD

**Issue by ADITYAMAHAKALI** [nayuki/QR-Code-generator#136]
I know this is not the right place to ask this but I have reach a dead end.

**Comment by nayuki** [comment]
All of the code in this library is cross-platform. There is no assembly language and no x86-specific code.

For example, if you want to use the TypeScript/JavaScript port, simply run it in a web browser on your M1 Mac.

For example, if you want to use the C++ port, install a C++ compiler on your system, then compile my C++ library.

You are responsible for setting up the development tools and runtime environment on your machine.

**Comment by YourMJK** [comment]
There is also a Swift implementation here if you want to use this in a native macOS application:  
https://github.com/BlockchainCommons/QRCodeGenerator
