### ISSUE TITLE
Any plans to make new release? 🤔 

### ISSUE THREAD

**Issue by kloczek** [nayuki/QR-Code-generator#137]
Loks like in the repo already os accumulated +100 commits.
IMO it would be good to flush all thse changes and make new release 😃

**Comment by kloczek** [comment]
> The last release of [v1.7.0](https://github.com/nayuki/QR-Code-generator/commit/4d13c303dc878ffae8df6d0e0a7513fe860a092c) was on 2021-08-08, about half a year ago. Reviewing my pile of commits from then till [now](4e41cb2c721a5e06eff75e79fd47a4274f6bb8b0)

Sometimes it is really healty to make new release to not accumuulate to much fo next release 😄

**Comment by nayuki** [comment]
Done: [v1.8.0](https://github.com/nayuki/QR-Code-generator/releases/tag/v1.8.0) @ [commit 720f62bddb72](https://github.com/nayuki/QR-Code-generator/tree/720f62bddb7226106071d4728c292cb1df519ceb).

**Comment by kloczek** [comment]
Just tested and new version builds correcrly.
Thank you.😃
