### ISSUE TITLE
Expiry & Clicks/User Limitation

### ISSUE THREAD

**Issue by iwanikhalid** [nayuki/QR-Code-generator#148]
Hi @nayuki if you don't mind me asking, the QR codes generated by your generator doesn't have any limitation in terms of expiry date, click amount and user open, right?

It's great and easy to use btw :)

**Comment by nayuki** [comment]
You are correct on all 3 counts.

A QR Code represents a piece of text. If the text is the real URL you want, then it cannot change or expire.  
If the text is a tracking URL hosted by someone else's server, then that server can behave arbitrarily.
