### ISSUE TITLE
I need heelp

### ISSUE THREAD

**Issue by AdamTeodoro** [nayuki/QR-Code-generator#150]
Hi, Its possible generate QRCode by one big string of 4MB?

**Comment by nayuki** [comment]
No, a QR Code can hold up to 2953 bytes. https://en.wikipedia.org/wiki/QR_code#Storage

**Comment by AdamTeodoro** [comment]
and if the image size is larger ? XD

**Comment by nayuki** [comment]
The maximum size of a QR Code is version 40. It can hold up to 2953 bytes of data.

**Comment by AdamTeodoro** [comment]
And if use the diferent colors from upgrade size :'(
