### ISSUE TITLE
Have a parameter to control the radius

### ISSUE THREAD

**Issue by hadithmv** [nayuki/QR-Code-generator#151]
This library has a lot of nice features and parameters, although I think most people would change a parameter like radius (which is missing) over the other optional parameters available in this.

Example of radius control parameter in another library:
https://nimiq.github.io/qr-creator/demo/

**Comment by nayuki** [comment]
Not a legal feature of QR Code according to the standard.

Graphical and stylistic options have always been rejected.
* https://github.com/nayuki/QR-Code-generator/issues?q=is%3Aissue+is%3Aclosed
* https://github.com/nayuki/QR-Code-generator/pulls?q=is%3Apr+is%3Aclosed

**Comment by hadithmv** [comment]
I see. I thought that since there were options for styling the code itself with color this might have been something similar. But I understand your reasoning.
