### ISSUE TITLE
Publish the rust-no-heap version to crates.io

### ISSUE THREAD

**Issue by Finomnis** [nayuki/QR-Code-generator#157]
Both of them claim to be [qrcodegen-1.8.0](https://docs.rs/qrcodegen/1.8.0/qrcodegen/), but only the `std` version is actually published on crates.io.

Would it be possible to publish the `no-std` version as well? For example with the name `qrcodegen-no-std`, or with a feature flag?

**Comment by nayuki** [comment]
No. https://github.com/nayuki/QR-Code-generator/issues/138
