### ISSUE TITLE
print_qr() function is missing from qrcodegen.py

### ISSUE THREAD

**Issue by joeybcrab** [nayuki/QR-Code-generator#163]
the print_qr() function is missing from qrcodegen.py

It was easy enough to grab it from the demo file, but jusy fyi :) Thank you for the beautiful code!

**Comment by nayuki** [comment]
The omission is intentional. I don't want to endorse any particular way to turn a QR Code into an image - whether it's exporting a bitmap file, an SVG string, printing to console, etc.
