### ISSUE TITLE
Availability of rust-no-heap on crates.io

### ISSUE THREAD

**Issue by tomgilligan** [nayuki/QR-Code-generator#169]
Not a super pressing issue but trying to use this library in an embedded rust project, I wasn't able to add `qrcodegen = "1.8.0"` to dependencies in `Cargo.toml`.

I was still able to use QR-Code-generator in my project but it was by cloning the repo from Github and importing `rust-no-heap` as a path on the local filesystem.  This is completely fine but for extra convenience it would be nice if it was also directly available on `crates.io`.

**Comment by nayuki** [comment]
https://github.com/nayuki/QR-Code-generator/issues/138 , https://github.com/nayuki/QR-Code-generator/issues/157
