### ISSUE TITLE
C Port did not compile on Apple M2 / Ventura 13.2

### ISSUE THREAD

**Issue by staatzstreich** [nayuki/QR-Code-generator#170]
Hi there,

thanks for this awesome project :)
because I want to use a QR code in a game I will made with raylib, I started to generate the lib with the shipped makefile.

I am sorry... i am not an expert with c programming nor with makefiles but I figured out that removing the double dashes in line 76 in https://github.com/nayuki/QR-Code-generator/blob/master/c/Makefile the `make all` works and the demo program also...

best,
Michael

**Comment by nayuki** [comment]
Thanks for the feedback. A permalink to the line of code: https://github.com/nayuki/QR-Code-generator/blob/0dbd3b2133180e55e6b5abc4eabe1b78abfc5cac/c/Makefile#L76

Related issues in the past: https://github.com/nayuki/QR-Code-generator/issues/95 , https://github.com/nayuki/QR-Code-generator/issues/43

**Comment by staatzstreich** [comment]
thx for pointing me to the related issues in the past 💯
