### ISSUE TITLE
Custom shapes support

### ISSUE THREAD

**Issue by Crovitz** [nayuki/QR-Code-generator#178]
I'd like to ask if there is a plan for adding custom shapes for QR code, like dots, round, or even perhaps some labels under the code?
Like below:
<img width="587" alt="image" src="https://user-images.githubusercontent.com/34936232/225316876-19f37a1f-c386-49e2-bb7c-adfa3209bbf2.png">

If not, maybe you could recommend how to achieve that?

**Comment by nayuki** [comment]
https://github.com/nayuki/QR-Code-generator/issues/113 , https://github.com/nayuki/QR-Code-generator/issues/167 , https://github.com/nayuki/QR-Code-generator/issues/116 , https://github.com/nayuki/QR-Code-generator/issues/77 , https://github.com/nayuki/QR-Code-generator/issues/27
