### ISSUE TITLE
How can I generate urls or svg tags required for img tags

### ISSUE THREAD

**Issue by laterdayi** [nayuki/QR-Code-generator#182]
So far it looks like it's all canvas. How can I generate urls or svg tags for img tags

**Comment by nayuki** [comment]
Look at the demo program for the language of your choice.

**Comment by laterdayi** [comment]
I really want to use this library, can you provide some demo

1. Customize the width and height of the QR code
2. Add some ICONS in the center of the QR code

I really hope you can help

@nayuki

**Comment by nayuki** [comment]
https://github.com/nayuki/QR-Code-generator/blob/22fac31bdf81da68730c177c0e931c93234d2a30/typescript-javascript/qrcodegen-input-demo.ts#L169-L188

No further free help will be provided.
