### ISSUE TITLE
Support Embeded Logo Image

### ISSUE THREAD

**Issue by hantsy** [nayuki/QR-Code-generator#185]
Some QRCode includes a specific logo image in QrCode to indicate the owner of QrCode, such a person photo, a company logo etc.

**Comment by hantsy** [comment]
eg. https://www.qrcodechimp.com/

**Comment by nayuki** [comment]
No. Browse historical answers: https://github.com/nayuki/QR-Code-generator/issues?q=is%3Aissue+is%3Aclosed
