### ISSUE TITLE
MicroQR support?

### ISSUE THREAD

**Issue by spiroyster** [nayuki/QR-Code-generator#186]
Hi,

Very much like your cpp QR generation. Working great, easy to follow, much appreciated! 
Would there be any support for MicoQR in the future?

**Comment by nayuki** [comment]
Nope, I won't add support for making Micro QR Code symbols. It looks like very few scanner software can read them. Consequently, no one else publishes them.

This topic has been raised in past issues. https://github.com/nayuki/QR-Code-generator/issues?q=is%3Aissue+is%3Aclosed
