### ISSUE TITLE
Publish the `rust-no-heap` crate on crates.io

### ISSUE THREAD

**Issue by ivmarkov** [nayuki/QR-Code-generator#188]
Background: I would've copy-pasted the code in [the project](https://github.com/project-chip/matter-rs/compare/main...ivmarkov:matter-rs:qr), if it wasn't that the project is licensed under Apache 2.0 only, while the QR code is licensed under MIT only.

Also, I can publish the code myself (using a fork), but it just doesn't feel right. So if you are up for it, maybe two options:
* Option A: a `qrcodegen-no-heap` (or whatever name we come up with) crate next to the already published `qrcodegen`
* Option B: Get `qrcodegen-no-heap` and `qrcodegen` mixed into a single crate/project with two modules, where the `qrcodegen` module is conditionally enabled when the `std` feature of the project is enabled (and the `std` feature is - as usual - in the crate's `default = ["std"]` feature); the `qrcodegen_no_heap` module (or however you might decide to name it) would always be enabled, of course

**Comment by nayuki** [comment]
Done with option A. https://github.com/nayuki/QR-Code-generator/pull/181#issuecomment-1685357764 , https://crates.io/crates/qrcodegen-no-heap

**Comment by ivmarkov** [comment]
I can confirm that the newly-published crate works great - thanks a lot!
