### ISSUE TITLE
Split data into multiple QR-codes using structured append mode

### ISSUE THREAD

**Issue by repolevedavaj** [nayuki/QR-Code-generator#195]
Is there any plan to support splitting data into multiple QR-codes using the structured append mode?

**Comment by nayuki** [comment]
No plans. Are there any readers that support it? Does anyone want this feature?

**Comment by repolevedavaj** [comment]
We have a use-case where we would like to use QR-codes to transfer data, but as the data exceeds the max content limitation of one QR-code, we would like to split the data into multiple. XZing actually supports reading such QR-codes, but I believe you just get the metadata and need to join the content together by yourself.

As far as I understood, structured append QR-codes just have some additional metadata, but apart from that, are not different to other QR-codes. So maybe it would be enough to allow setting these bytes and do the split outside of the lib? If you like, I can try to create a PR for allowing that, what do you think?

**Comment by nayuki** [comment]
I'm hesitant to support more functionality, as it is a commitment to implementing this 7 times over, and maintaining it forever.

You are more than welcome to fork the library and implement the feature yourself, with no warranty from me of course. You probably want to implement a new type of `QrSegment` like `Mode.ECI`.

**Comment by repolevedavaj** [comment]
OK I will take a look - what's the difference between the fast java implementation and the normal one?

**Comment by nayuki** [comment]
https://www.nayuki.io/page/qr-code-generator-library#java-fast , https://www.nayuki.io/page/fast-qr-code-generator-library
