### ISSUE TITLE
I would like to create a simple android app using your QR-Code-generator ... is it possible ?

### ISSUE THREAD

**Issue by aiamuzz** [nayuki/QR-Code-generator#196]
@nayuki ... great project especially for replicating this on various coding platforms meticulously !!!

I am a CS graduate but never turned a coder but i do hope to learn Android programming, i came across your project on QR Code ... will it be possible to integrate your QR Code generator project into my simple android app ?

thanks for looking.

**Comment by nayuki** [comment]
Android is based on Java. You can import Java source files directly into your project.

I haven't done any Android development myself, so I can't say anything further.
