### ISSUE TITLE
Letters get wrongly encoded as Kanji

### ISSUE THREAD

**Issue by jonas1015119** [nayuki/QR-Code-generator#199]
When including non-ascii letters like ä, ö, ü or ß they and the next letter following them get encoded as a Kanji character.
"Blüte" turns into "Bl鬱e" and so on. (the Kanji seem to change based on which two letters get absorbed)

Tested in the live demo, is there an option in the full version that would fix this?

**Comment by nayuki** [comment]
Your example text has no problem when I scan using Android's [Barcode Scanner app](https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=en_CA&gl=US).

What scanner app are you using? Maybe it is assuming a character encoding other than UTF-8.

**Comment by jonas1015119** [comment]
tested a bit more, it seems to be an issue with the integrated qr code
reader of my camera app, when switching to Google lens it works fine.
probably incorrect encoding as you said.

thanks!


Nayuki ***@***.***> schrieb am Sa., 20. Jan. 2024, 00:46:
