### ISSUE TITLE
please create LICENSE file

### ISSUE THREAD

**Issue by j256** [nayuki/QR-Code-generator#203]
Hi.  Thanks much for the code.  Please consider copying the license out of the README and to a LICENSE file so that github can detect it and recognize it as MIT.  Thanks!

**Comment by nayuki** [comment]
Politely declined on these grounds:

* Reducing the number of files in the project to a minimum.
* Naming files in ALL CAPS is a bad habit from Unix.
* Having no file extension imply that it's a text file is also a bad Unix-ism.
* I am fully aware of standard project files like AUTHORS, LICENSE, COPYING (all in all-caps, no extension) by convention. This is a conscious choice to reject the convention.
* I reformatted the MIT License, and GitHub might not recognize it as the MIT License.

**Comment by nibazshab** [comment]
If not this

> Reducing the number of files in the project to a minimum.

GitHub can recognize the name like `License.txt`

**Comment by j256** [comment]
> Reducing the number of files in the project to a minimum.

Why?

> Naming files in ALL CAPS is a bad habit from Unix.

You know that they work however right?  Think `Makefile`.  Feel free to make it `License.txt`.  The point of course is to have this important file move to the top of the file list on purpose.

> Having no file extension imply that it's a text file is also a bad Unix-ism.

Think Makefile again.  Or README.  Again feel free to make it `License.txt`.

> This is a conscious choice to reject the convention.

Sigh.  Conventions help others.  So your opinions about what is "right" cause more work for your users.

>  I reformatted the MIT License, and GitHub might not recognize it as the MIT License.

One way to find out.
