### ISSUE TITLE
Pure JavaFX WriteImage code

### ISSUE THREAD

**Issue by kermiedefrog** [nayuki/QR-Code-generator#33]
added this code for my project ... so thought I would give it back to you .. I couldn't use any AWT classes which BufferedImage is ... 
```Java
 public WritableImage toWritableImage(int scale, int border)
    {
        if (scale <= 0 || border < 0)
        {
            throw new IllegalArgumentException("Value out of range");
        }
        WritableImage image = new WritableImage((size + border * 2) * scale, (size + border * 2) * scale);
        for (int y = 0; y < image.getHeight(); y++)
        {
            for (int x = 0; x < image.getWidth(); x++)
            {
                boolean val = getModule(x / scale - border, y / scale - border);
                image.getPixelWriter().setColor(x, y, val ? Color.BLACK : Color.WHITE);
            }
        }
        return image;
    }
```

**Comment by nayuki** [comment]
Thanks for the info. I haven't been following up on JavaFX at all; I learned Java during the AWT+Swing days of JDK 1.4. Are you saying that java.awt.BufferedImage is not available in your programming environment? If so, please describe your situation so I can better understand why my code might not work for everyone.

**Comment by msgilligan** [comment]
@nayuki I think the problem with using ` java.awt.BufferedImage` is you have to convert it:  https://stackoverflow.com/questions/30970005/bufferedimage-to-javafx-image

**Comment by kermiedefrog** [comment]
Gluon - or JavaFX mobile, doesn't support AWT classes at all ...
