### ISSUE TITLE
Error in Makefile using (ar) utility for Mac.

### ISSUE THREAD

**Issue by snOm3ad** [nayuki/QR-Code-generator#43]
The Makefile contains the following (on line 72)
`$(LIBFILE): $(LIBOBJ) 
          $(AR) -crs $@ -- $^`
The command fails on MacOS High Sierra because the `ar` utility does not recognize the `--` as valid syntax. Removing the double dash, solved the issue for me.

**Comment by IlyaDiallo** [comment]
> Yeah, I saw the same problem with `ar` and `--` on OpenBSD. But using `--` to end the list of flags is supported in many programs (a GNU-ism maybe?), and adds to the robustness against accidental flags.

Is the purpose of the `--` solely to "add robustness again accidental flags" (on Linux) ?
If so, is it worth it, considering that it's an invalid syntax on other systems ?
