### ISSUE TITLE
Missing include header stdexcept in cpp

### ISSUE THREAD

**Issue by h46incon** [nayuki/QR-Code-generator#44]
In `QrCode.hpp`, reference of `std::length_error` is defined in header `stdexcept`. 

ref: https://en.cppreference.com/w/cpp/error/length_error

**Comment by nayuki** [comment]
Thank you so much for pointing this out. I fixed it now in https://github.com/nayuki/QR-Code-generator/commit/ec729bf2695300691f4b3a96ba5eaba083ebec00 .

**Comment by h46incon** [comment]
Thanks for your quick response.
