### ISSUE TITLE
[Java] Make dependency on BufferedImage optional for Android Support

### ISSUE THREAD

**Issue by iddo** [nayuki/QR-Code-generator#46]
The only thing preventing this project from being Android compatible is its dependency on BufferedImage, a simple change to make the output generator pluggable will open up this library for Android projects.

Only usage of BufferedImage is [here](https://github.com/nayuki/QR-Code-generator/blob/ec729bf2695300691f4b3a96ba5eaba083ebec00/java/src/main/java/io/nayuki/qrcodegen/QrCode.java#L299)

**Comment by jamorham** [comment]
Does this work for Android? I quickly put it together for a project:

gradle via jitpack: 
`implementation 'com.github.jamorham:QR-Code-generator:d0454644af'`

https://github.com/jamorham/QR-Code-generator

I removed all the non-java code, the dependency on `BufferedImage` and some other items related to Kanji characters that used java constructs which I don't think are available in all Android versions.

**Comment by plmkojx** [comment]
> Does this work for Android? I quickly put it together for a project:
> 
> gradle via jitpack:
> `implementation 'com.github.jamorham:QR-Code-generator:d0454644af'`
> 
> https://github.com/jamorham/QR-Code-generator
> 
> I removed all the non-java code, the dependency on `BufferedImage` and some other items related to Kanji characters that used java constructs which I don't think are available in all Android versions.
             Hello how do I use it in AndroidStudio

**Comment by nayuki** [comment]
Probably fixed in https://github.com/nayuki/QR-Code-generator/commit/da7ad83c5cae39821ed2f389634b8fd159e45374 .

**Comment by nayuki** [comment]
Also related to https://github.com/nayuki/QR-Code-generator/commit/010410be0244769db0a1efbc7eb78833e31b85bf .
