### ISSUE TITLE
Deprecated use of # on chrome version 72

### ISSUE THREAD

**Issue by zahnno** [nayuki/QR-Code-generator#49]
The fill on svg rect is causing issues rendering the svg on chrome version 72

Changing the fill to use rgb instead fixes the issue.

**Comment by nayuki** [comment]
Hi, in the future if you have a problem and a fix at the same time, you should roll them into a single pull request - no issue needed.

**Comment by zahnno** [comment]
Whatever your preference is 👍 it's your project.
