### ISSUE TITLE
Thanks for your works

### ISSUE THREAD

**Issue by xusiwei** [nayuki/QR-Code-generator#5]
I use your qrcodegen C++ codes in my recently [project](https://github.com/ftmdevlopment/rftm).
It's a test program running on an Android based device, which start up directly from init process(configured in `init.factory-mode.rc`).

Great Thanks for your works!

BR

Siwei Xu(at Hangzhou, China)

**Comment by nayuki** [comment]
You're welcome! Feel free to send me an email next time instead of opening an issue.
I see the code used in https://github.com/ftmdevlopment/rftm/tree/master/jni/qrcode

**Comment by xusiwei** [comment]
Yes, thanks and regards!
