### ISSUE TITLE
Output result in fixed size (javascripts)

### ISSUE THREAD

**Issue by thejustsoul** [nayuki/QR-Code-generator#52]
Is it possible to change the demo so that the output image has a fixed size (for saving in png), let's say 350x350, 230x230, 120x120, etc. px? So that the picture does not increase after entering information.

**Comment by nayuki** [comment]
No, this behavior is not supported. For the simplicity of the implementation, I will not change the way drawCanvas() or the demo works.

You are free to implement your own code to read the size of the QrCode object and calculate the appropriate scale factor for rendering.

**Comment by thejustsoul** [comment]
I am not a JS programmer, and I can’t write such code, it’s a pity :-(
It suits everyone (for personal needs), except for the impossibility to set a fixed size of the output image..

**Comment by nayuki** [comment]
You are free to solicit help and/or hire a programmer.
I will not be responsible for fulfilling this feature request.
