### ISSUE TITLE
Converting qrcode to Raw image buffer (RGBA_8888)

### ISSUE THREAD

**Issue by karthikrish9** [nayuki/QR-Code-generator#55]
Hello 

Thank you for the amazing work.  I have a requirement in my project where I have to generate QR code and display it on a screen, but I am stuck because I don't have any experience with graphics. Perhaps you can help me with this problem? 

Problem: We have following API which takes the raw image buffer of pixels in the RGBA_8888 format and draw it in the screen. So I could use  `qrcodegen_encodeText("Helloworld", tempBuffer, qrcode, errCorLvl, qrcodegen_VERSION_MIN, qrcodegen_VERSION_MAX, qrcodegen_Mask_AUTO, true);
` and then how do I convert `qrcode` to  `Raw image buffer` (C Structure `RawImage_t` shown below) with Pixel format `RGBA_8888`? 

Following is the API and RawImage_t format description. I would really appreciate if you can give pointers on how to do this?  Thanks a lot in advance. 

```
**
 * @brief                   Draw a raw image buffer of pixels at (dx:dy) into a drawing buffer. This function requires a valid graphic context. The pixel format is fixed to RGBA_8888 (red channel  first in memory).
 */
Result DrawBufferOnScreen(
    GraphicContext_t graphicContext,  //Graphic context.
    const RawImage_t *pRawImage ,  // Raw image buffer to be drawn.
    int32_t dx,                                  //X coordinates of the top-left corner of the raw image
    int32_t dy);                               //  Y coordinates of the top-left corner of the raw  image 

typedef struct {
    void        *data;      /**< A buffer containing the pixels. */
    uint32_t    size;       /**< Size of the buffer. */
    uint32_t    pixelFormat;/**< Pixel format in RGBA_8888 */
    uint32_t    stride;     /**< Image stride (number of bytes in the buffer
                              between the beginning of a line and the beginning
                              of the next line). */
    uint32_t    width;      /**< Image width in pixels. */
    uint32_t    height;     /**< Image height in pixels. */
} RawImage_t, *RawImage_ptr;
```

**Comment by nayuki** [comment]
Hi, thank you for your polite request. I would like to remind you that although I published this library for free, you should not expect me to provide free advice for your own problems. Please do not solicit open-source authors like this in the future; please have something to offer instead.

It's good you pointed out your inexperience with graphics. An image buffer is basically a 2D matrix of numbers. You have to draw stuff pixel by pixel using a for-loop. You definitely want to use my `qrcode_getPixel()` function to read out the black/white squares in the QR Code.

See my Java code for a *sketch* of what you should be doing, even though you would write different code in C. https://github.com/nayuki/QR-Code-generator/blob/04e1942b16a32fc8f38513665a0c98c50e17ace7/java/src/main/java/io/nayuki/qrcodegen/QrCode.java#L305

Feel free to ask https://stackoverflow.com/questions/ask if you need additional help.
