### ISSUE TITLE
error: 'for' loop initial declaration used outside C99 mode

### ISSUE THREAD

**Issue by HosseinAssaran** [nayuki/QR-Code-generator#59]
When compiling qrcodegen.c with arm-brcm-linux-gnueabi-gcc, I get this error: 
```error: 'for' loop initial declaration used outside C99 mode```
that shows default compile mode is not compatible with this code.

**Comment by nayuki** [comment]
Use C99 on your compiler. We live in year 2019 already. Stop defaulting to C89.

**Comment by nayuki** [comment]
Observe that my sample Makefile explicitly says you shall use `-std=c99`.

https://github.com/nayuki/QR-Code-generator/blob/be143456be73140d4c9979f4f5e12f409acd71e4/c/Makefile#L32
