### ISSUE TITLE
needs different names for the C vs. C++ libs

### ISSUE THREAD

**Issue by reneengelhard** [nayuki/QR-Code-generator#63]
AFAICS:

C lib: libqrcodegen.a
C++ lib: libqrcodegen.a

Which would conflict when both installed in /usr/lib (to use this lib)

Debian (as I found out, I am not the maintainer of the package) has https://sources.debian.org/src/qr-code-generator/1.4.0-1/debian/patches/cpp-lib.patch/?hl=25#L25 as a patch to rename the C++ lib to libqrcodegencpp.

[ and it also invents a shared library, this is not ideal, but... Probably because unox uses the lib, too - could have built against a static library, too.... ]

**Comment by Avantika782** [comment]
I want to contribute to this issue please assign it to me.

**Comment by nayuki** [comment]
Fixed in https://github.com/nayuki/QR-Code-generator/commit/5300e400eca9b8b4a9e8c0d4c3b03883d4749238 .
