### ISSUE TITLE
Asan flags are not production flags

### ISSUE THREAD

**Issue by asarubbo** [nayuki/QR-Code-generator#64]
https://www.openwall.com/lists/oss-security/2016/02/17/9

**Comment by nayuki** [comment]
True, I've been rethinking about what to put in my makefile.

How is this perspective?: The provided makefile is a demonstration of how to compile the library and example programs. It comes with strict flags for me to assure quality. The makefile should be an example to guide you on scripting a production build, but it should not be used in an unmodified form for a production build.

**Comment by asarubbo** [comment]
The majority of users simply type make.

I'd suggest to move the asan flags into a debug phase, so to test with asan flags you need to type make debug.

**Comment by nayuki** [comment]
Okay, sounds good! Thanks for letting me know that Asan is a vulnerability when being run in production.

**Comment by nayuki** [comment]
Fixed in https://github.com/nayuki/QR-Code-generator/commit/7eac8beffeb935de5a2fdd65656d8cb500b0abda .
