### ISSUE TITLE
Base64 png for c++

### ISSUE THREAD

**Issue by riddheshganatra** [nayuki/QR-Code-generator#66]
Thanks a lot for this superb work!!!

I am trying to write node js addon in c++ and want to save QRcode image in base64 format.

I have to generate more than 100000 QR codes at once, any possible solution will be helpful.

Thanks in advance.

**Comment by nayuki** [comment]
Sorry, no help provided. You need to chain together some libraries by yourself.

**Comment by riddheshganatra** [comment]
Thanks a lot for a quick response.
Really appreciate
