### ISSUE TITLE
How to save the generated QR code image?

### ISSUE THREAD

**Issue by zanazakaryaie** [nayuki/QR-Code-generator#67]
Hi. Thanks for publishing this useful library.

I want to use it in C++. The QrCodeGeneratorDemo.cpp only shows how to print it in the console. Is there any way to save the image instead of printing in the console?

**Comment by nayuki** [comment]
You'll need to grab the QR Code pixels and connect a library like libpng.

There are too many possible image formats people want, so I will not endorse any particular one by putting it in my library.

**Comment by zanazakaryaie** [comment]
Thanks for the reply. I can use OpenCV to save the image but I need the pixels first. Could you please help me how can I grab the pixel values?
