### ISSUE TITLE
Resize functionality to the QR code.

### ISSUE THREAD

**Issue by omsitapara23** [nayuki/QR-Code-generator#68]
Right now in the current implementation, the output of the qrCode depends on the version. Is there a way where we can leverage the current implementation and generate qr code based on user input Eg generate 200*200 pixel QR code?

**Comment by nayuki** [comment]
You can kind of do it. You need to read qrcode.size and do appropriate calculations and scaling.

**Comment by nayuki** [comment]
You can kind of do it. You need to read qrcode.size and do appropriate calculations and scaling.

I don't consider this to be an "issue" with my library. This is more of a feature request, or "please add functionality to the library so that I don't have to do the work myself".

**Comment by omsitapara23** [comment]
Hi, @nayuki I, with your permission, want to implement a new function in java to generate the user-defined QR code. if you have no objection please reply to me and I will implement it right away.

Thank you!
Om.
