### ISSUE TITLE
Make Java generator as a library

### ISSUE THREAD

**Issue by mariotaku** [nayuki/QR-Code-generator#7]
Thanks for this lightweight QR code generator!

Are you interested in making Java generator as a library? I can add gradle/maven config and make platform specific features (like Android specific feature) if you wish.

**Comment by nayuki** [comment]
I don't have experience with making formally packaged libraries and understanding how the tools work...
If you need to librarify it for your own project, feel free to go ahead and show me the result!

**Comment by glitchammer** [comment]
Hi, thanks for building this great module, first of all. I just made it a java library as to import it in my android project (the clean way). GitHub doesn't want me to add jar files to this message, so I can't "show you the result" just like that. Anyway, maven/gradle is certainly the way to go, just as @mariotaku already suggested. I like to offer you my support with that as well (although I'm not so confident with that step).

**Comment by tovine** [comment]
I'm actually working on this right now - I want to use it in my project and putting it into a Maven workflow is much more elegant than including sources.

@nayuki would you like to sign it with your own GPG key so "it's yours" when submitting to the central repository or do you just want me to push it so it's done?
The config used to deploy it to central will of course be included in my fork (and subsequent pull request), it's just a matter of who "signed" the push of this version. :slightly_smiling_face:

**Comment by nayuki** [comment]
I don't use GNU Privacy Guard nor have a private key, sorry.

**Comment by tovine** [comment]
I will just sign it with my key and push then, if it is okay with you?

**Comment by tovine** [comment]
Also, my fork is currently here: https://github.com/tovine/QR-Code-generator. I will submit a pull request once everything is approved and the maven groupId is fixed in the central repository.

**Comment by tovine** [comment]
Pull request is here: https://github.com/nayuki/QR-Code-generator/pull/26

**Comment by nayuki** [comment]
The [POM file was written](https://github.com/nayuki/QR-Code-generator/commit/8e54f6ffa656520ca85d4d58b7970a3e35bf0bed), and the library has been published to Maven Central tonight.

**Comment by AntonOellerer** [comment]
Hey,
First, thank you for this library!
Would it be possible to publish `fastqrgen` on maven as well?
Best regards
Anton

**Comment by nayuki** [comment]
@AntonOellerer, I will not be releasing fastqrcodegen on Maven Central because the library's speed-up makes no difference in the real world.

> This is an alternate, speed-optimized implementation of my QR library in Java. It contrasts with my standard/reference/slow library which optimizes for clarity and conciseness. The functionality of this fast library and its API are nearly identical to the other one, but it runs anywhere from 1.5× to 10× as fast. However, even the slow library takes less than 10 ms in the worst case, so the benefit of increasing speed is dubious at best.
> — https://www.nayuki.io/page/fast-qr-code-generator-library
