### ISSUE TITLE
zbar can't detect and decode the generated QR codes

### ISSUE THREAD

**Issue by zanazakaryaie** [nayuki/QR-Code-generator#71]
I used your library to create a QR code that encodes "00000". Zbar library can't detect or decode it. Next, I used https://www.the-qrcode-generator.com/ to generate the same text. Now, Zbar can detect and decode it
I compared the generated QR codes and they are not same! The first image is the one generated by your library and the second image is the one generated by https://www.the-qrcode-generator.com/.

![library](https://user-images.githubusercontent.com/25720728/69625540-0b3ffd00-105c-11ea-9176-883aa68814f9.png)

![http](https://user-images.githubusercontent.com/25720728/69625596-26127180-105c-11ea-9bb3-1abe7f92c774.png)

**Comment by nayuki** [comment]
* I was unable to reproduce your QR Code with the input text "00000" (without quotes). I used the online demo at https://www.nayuki.io/page/qr-code-generator-library (TypeScript/JavaScript). This is the exact same algorithm in all 6 languages I offer.

    Hence, please supply the source code for how you are calling my qrcodegen library so I can confirm that you get such an output.

* For a given piece of data, there are multiple valid ways to encode it as a QR Code. The mask selection offers 8 possibilities, the error correction level offers some possibilities, and the segmentation of substrings offers almost unlimited possibilities. Just because my output doesn't match another program does not automatically mean it's wrong. But indeed, if you say that the QR Code cannot be scanned, then it suggests something went wrong, possibly in your code or in my code.

* I successfully scanned both of your QR Codes in ZXing / Android Barcode Scanner app. The first one says "0" (contrary to what you wanted) (ECC H) and the second one says "00000" (ECC L).

**Comment by nayuki** [comment]
Can you provide more information, @zanazakaryaie?

**Comment by zanazakaryaie** [comment]
Hi
Sorry for my late reply
Let me send my cpp code. Maybe I'm doing something wrong.
[QrCodeGeneratorSaveImage.zip](https://github.com/nayuki/QR-Code-generator/files/3915186/QrCodeGeneratorSaveImage.zip)

**Comment by nayuki** [comment]
You provided:

```
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <string>
#include <vector>
#include "BitBuffer.hpp"
#include "QrCode.hpp"
#include <opencv2/opencv.hpp>

using namespace std;
using namespace cv;
using qrcodegen::QrCode;
using qrcodegen::QrSegment;


// Function prototypes
static void doBasicDemo(string text);
static void saveQrImage(const QrCode &qr, std::string fileName);



// The main application program.
int main() {


    for (size_t i=0;i<=12000;i+=100)
    {
        doBasicDemo(to_string(i));
    }

	return EXIT_SUCCESS;
}


// Creates a single QR Code, then prints it to the console.
static void doBasicDemo(string text)
{
    const QrCode::Ecc errCorLvl = QrCode::Ecc::MEDIUM;
	const QrCode qr = QrCode::encodeText(text.c_str(), errCorLvl);

	saveQrImage(qr, text);
}


static void saveQrImage(const QrCode &qr, string fileName)
{
	int border = 1;

	const int n = qr.getSize() + 2*border;
	cv::Mat output(n,n,CV_8UC1);

	for (int y = -border; y < qr.getSize() + border; y++)
	{
		for (int x = -border; x < qr.getSize() + border; x++)
		{
			//std::cout << (qr.getModule(x, y) ? "##" : "  ");
			qr.getModule(x, y) ? output.at<uchar>(x+border,y+border)=0 : output.at<uchar>(x+border,y+border)=255;
		}
	}

	Mat finalImage(1200, 1000, CV_8UC1);
	finalImage.setTo(255);
    resize(output, output, Size(950,950), 0,0, CV_INTER_NN);
    output.copyTo(finalImage(Rect(25,0,950,950)));

    char text[255];
    sprintf(text, "%05d", atoi(fileName.c_str()));
    putText(finalImage, text, Point(400,1000), CV_FONT_HERSHEY_COMPLEX, 2, Scalar(0), 5);

    rectangle(finalImage, Rect(50,1020,900,150), Scalar(0), 5);
    fileName = fileName+".png";
    imwrite(fileName, finalImage);
}
```

**Comment by nayuki** [comment]
Problem: You called `doBasicDemo(to_string(i));`, but you did not supply a definition of the `to_string()` function.

I am going to assume that `to_string(0)` returns "0", not "00000", because that's what your output QR Code looks like.

**Comment by zanazakaryaie** [comment]
That's right. It was a mistake. But even with "0" instead of "00000", why Zbar can't detect it?

**Comment by nayuki** [comment]
I think I figured it out. When you used my library, you switched the X and Y axes.

Zbar is probably stricter so it only decodes QR Codes that haven't been mirrored. Meanwhile, ZXing will happily decode QR Codes that are mirrored and/or rotated.

**Comment by nayuki** [comment]
I think I figured it out. You called my library, and then in the image rendering you switched the X and Y axes. Look at how your image differs from the demo console program that I supplied.

Zbar is probably stricter so it only decodes QR Codes that haven't been mirrored. Meanwhile, ZXing will happily decode QR Codes that are mirrored and/or rotated.

**Comment by zanazakaryaie** [comment]
Zbar is robust to the rotation but I'm not sure about the robustness to mirrored codes.
Anyway, thanks to the time you put for checking my code
