### ISSUE TITLE
QrSegmentAdvanced can produce sub-optimal results for Shift JIS

### ISSUE THREAD

**Issue by gitlost** [nayuki/QR-Code-generator#74]
First off thanks for the super algorithm for optimizing encoding modes, which is now being used in a number of places in [Zint](https://sourceforge.net/projects/zint/).

An issue I noticed while adapting it is that Byte mode in `computeCharacterModes()` assumes UTF-8 encoding. For instance the "kanji/European" example string "こんにちwa、世界！ αβγδ", which is fully encodable in Shift JIS, produces a segmentation of "K4 B2 K4 A1 K4", for a bit length of 239. A shorter segmentation is a single Shift JIS encoded segment "B27", with a bit length of 228.

**Comment by nayuki** [comment]
Hi, thanks for your feedback. I haven't heard of Zint before. I took a quick look at the project, and I guess the core of the QR Code related algorithms is in the source file: https://sourceforge.net/p/zint/code/ci/master/tree/backend/qr.c

I should note that the QR Code specification document contains an appendix that describes an algorithm (maybe optimal) for switching segments to minimize the output size. But my own implementation is not based on that; instead I worked out the dynamic programming problem from first principles, and it lets me understand the code and have high confidence that it is indeed optimal (for the 4 modes that I support).

Your claim about Shift JIS is correct. I only support 3 modes (numeric, alphanumeric, UTF-8 bytes) in my QR Code generator library, plus kanji mode only in the Java advanced version. I support custom ECI segments, but this must be performed manually. So what you can do is make an empty list of segments, add an ECI segment to switch to Shift JIS. Then take the text string, convert it to a byte array in Shift JIS, make a byte segment, and append it to the list of segments.

Of course, the dynamic programming optimization procedure can add more modes than the 4 I've implemented. But I do not wish to support legacy character encodings, which clutter conversion tables, add confusion, and are not international-oriented. I firmly believe in UTF-8 being the character encoding to end all encodings. (This includes my disdain for UTF-16.)

**Comment by gitlost** [comment]
If you're happy with it that's fine, just thought I'd mention it. Thanks again for the algorithm, which is a gem.
