### ISSUE TITLE
Make a tarball release

### ISSUE THREAD

**Issue by vitlav** [nayuki/QR-Code-generator#75]
Please make a tag with version and release tarball.

**Comment by nayuki** [comment]
* For which language(s)? (e.g. C, C++ users expect tarballs. Python users expect PyPI.)
* Who is the audience? (e.g. packaging for Linux distributions)
* I don't break the build or introduce bugs, so why is nightly not good enough?

**Comment by nayuki** [comment]
My follow-up questions to your request:

* For which language(s)? (e.g. C, C++ users expect tarballs. Python users expect PyPI.)
* Who is the audience? (e.g. packaging for Linux distributions)
* I don't break the build or introduce bugs between officially tagged releases. Anyone can use my nightly snapshots, and that should be good enough, right?

**Comment by vitlav** [comment]
> * For which language(s)? (e.g. C, C++ users expect tarballs. Python users expect PyPI.)
Just set a tag on a last good commit. Then github automagically public tarballs with the repository snaphot.
> * Who is the audience? (e.g. packaging for Linux distributions)
Yes, packaging for Linux distibutions. Almost packaging system needs a version of a package.

> * I don't break the build or introduce bugs between officially tagged releases. Anyone can use my nightly snapshots, and that should be good enough, right?
Hmm... It is enough you set tags. But why there are no tarballs like here https://github.com/Etersoft/eepm/releases ?

**Comment by vitlav** [comment]
Oh, sorry. It looks like I am a bind man. I miss release tab on the page!
All is ok.
Thank you for the project!

**Comment by nayuki** [comment]
For reference, these are the answers:
* https://github.com/nayuki/QR-Code-generator/releases
* https://github.com/nayuki/QR-Code-generator/tags
