### ISSUE TITLE
Allow different dot/square designs

### ISSUE THREAD

**Issue by jbnjohnathan** [nayuki/QR-Code-generator#77]
I have seem some QR codes that for each black square, the squares edges are rounded. This makes for a different and more aesthetic look.
Attaching a picture to show what I mean.

To allow different designs of the squares would be really nice

![2020-02-11 17_19_53-Photos](https://user-images.githubusercontent.com/54041505/74255861-c474b180-4cf2-11ea-885d-896daef315ab.png)

**Comment by nayuki** [comment]
I understand what you're asking for. Sorry, this is a computational library, not an aesthetics library. Trying to cater to every possible desire is too costly for too little benefit. You are welcome to loop over the QR Code matrix, call `getModule(int x, int y)`, and do custom rendering.

**Comment by mahmoudafer** [comment]
hi @jbnjohnathan, did you successfully manage to change the design?

**Comment by jbnjohnathan** [comment]
> hi @jbnjohnathan, did you successfully manage to change the design?

Hi. No I haven't so far. Seems a bit too complicated for me right now with the way suggested by nayuki.

**Comment by mahmoudafer** [comment]
It seems I'm managing to successfully do it, when I get more insights I'll share with you

**Comment by jbnjohnathan** [comment]
> It seems I'm managing to successfully do it, when I get more insights I'll share with you. Never thought I'll have to learn about HTML5 canvas or svg yet here i am xP

Cool, that would be very valuable!

**Comment by primecodecom** [comment]
Using [c++](https://github.com/nayuki/QR-Code-generator/tree/master/cpp) implementation of library, I made some changes. 
[Updated library is here
](https://www.npmjs.com/package/@primecode/async-qrcode)
1. Update the code to work with AsynWorker, so the code could execute in different thread and build it to node js addon. 
2. Added 3 different type of style dots 
 <img src="https://github.com/primecodecom/files/raw/master/ROUND.png" width="120" height="120">
<img src="https://github.com/primecodecom/files/raw/master/SQUARE.png" width="120" height="120">
<img src="https://github.com/primecodecom/files/raw/master/CIRCLE.png" width="120" height="120">
3. Different color styles
<img src="https://github.com/primecodecom/files/raw/master/COLORED.png" width="120" height="120">
