### ISSUE TITLE
Provide TypeScript build instructions (for Windows)

### ISSUE THREAD

**Issue by gnbl** [nayuki/QR-Code-generator#96]
Please add instructions to compile the typescripts on Windows (10):

- Install node.js https://nodejs.org/en/download/
- open CMD/powershell
- Install typescript: https://www.typescriptlang.org/#installation
   `npm install -g typescript`
- install dependency `npm install @types/node`
- [add to environment variables: https://stackoverflow.com/questions/36753867/running-tsc-from-the-windows-command-line or
invoke via `npx tsc`(not tested)]

- compile (as in `build.sh`):
   ` tsc.cmd --strict --lib DOM,DOM.Iterable,ES6 --target ES6 qrcodegen.ts qrcodegen-input-demo.ts`
   `tsc.cmd --strict --lib DOM,DOM.Iterable,ES6 --target ES6 qrcodegen.ts qrcodegen-output-demo.ts`
   ` tsc.cmd --strict --target ES2017 --outFile qrcodegen-worker.js qrcodegen.ts qrcodegen-worker.ts`

qrcodegen.js is 48 kB.

Minify (default options, I know nothing about these tools):

` npm install terser -g`
` terser.cmd qrcodegen.js --compress --mangle -o qrcodegen.min.js`

reduces it to 12 kB, and the "input" demo works with default settings (others not tested). File attached (no warranty).

Except for the installation of nodejs, this probably could be done with a batch file.

The demos:
- "input" is like https://www.nayuki.io/page/qr-code-generator-library
- "output" generates a set of codes

Fantastic project, thanks! I'll try the Python version next.

[qrcodegen.min.js.zip](https://github.com/nayuki/QR-Code-generator/files/5166803/qrcodegen.min.js.zip)

**Comment by nayuki** [comment]
Thanks for the detailed notes! I'll keep this in mind when I review my documentation.

**Comment by Connum** [comment]
It would also be great if the transpiled JS version was available in the releases tab here on GitHub, containing a minified and a non-minified version for easier access.

**Comment by nayuki** [comment]
@Connum Thanks for the suggestion! I started making use of GitHub's releases feature, and added compiled JavaScript files. https://github.com/nayuki/QR-Code-generator/releases/tag/v1.6.0

**Comment by Connum** [comment]
> @Connum Thanks for the suggestion! I started making use of GitHub's releases feature, and added compiled JavaScript files. https://github.com/nayuki/QR-Code-generator/releases/tag/v1.6.0

This is great, thanks for the super-quick reaction!

**Comment by 10000multiplier** [comment]
@greggman awesome! Any chance for a react-native example?

**Comment by zamicol** [comment]
This is how I'm 1. building the Javascript file, 2. minifying using `esbuild` and 3. Adding UMD module support ([one liner](https://github.com/Cyphrme/qrgenjs/blob/d05054f5fd2842ccded90795724dd7a3b19ffbea/module_append.txt)): 
```
tsc --strict --lib DOM,DOM.Iterable,ES6 --target ES6 1.8.0/ts/qrcodegen.ts --outFile 1.8.0/qrgen.js
esbuild 1.8.0/qrgen.js --minify --outfile=1.8.0/qrgen.min.js && cat module_append.txt >> 1.8.0/qrgen.min.js
```
